app/config/__init__.py
from .routes import (
    dashboard_bp,
    auth_bp,
    settings_bp,
    users_bp,
    groups_bp,
    articles_bp,
    analytics_bp,
)

app/config/routes.py
from flask import (
    Blueprint,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from app.config.utils import is_logged_in, login_not_required, mysql, MySQLdb, is_admin
from app.controller.analytic import data_analytic
from app.controller.auth import auth_login, auth_logout
from app.controller.dashboard import dashboard_index
from app.controller.article import data_article
from app.controller.group import group_index
from app.controller.user import admin_index, operator_index, viewer_index

auth_bp = Blueprint("auth", __name__, template_folder="../templates")
dashboard_bp = Blueprint("dashboard", __name__, template_folder="../templates")
settings_bp = Blueprint("setting", __name__, template_folder="../templates")
users_bp = Blueprint("user", __name__, template_folder="../templates/user")
groups_bp = Blueprint("group", __name__, template_folder="../templates")
articles_bp = Blueprint("article", __name__, template_folder="../templates")
analytics_bp = Blueprint("analytic", __name__, template_folder="../templates/analytic")


# auth
@auth_bp.route("/login", methods=["GET", "POST"])
@login_not_required
def index():
    return auth_login()


# dashboard
@dashboard_bp.route("/")
@is_logged_in
def index():
    return dashboard_index()


# user
@users_bp.route("/admin", methods=["GET", "POST"])
@is_logged_in
@is_admin
def admin():
    return admin_index()


@users_bp.route("/operator", methods=["GET", "POST"])
@is_logged_in
@is_admin
def operator():
    return operator_index()


@users_bp.route("/viewer", methods=["GET", "POST"])
@is_logged_in
@is_admin
def viewer():
    return viewer_index()


# group
@groups_bp.route("/", methods=["GET", "POST"])
@is_logged_in
def index():
    return group_index()


# settings
@settings_bp.route("/profile")
@is_logged_in
def profile():
    return render_template("profile.html")


# article
@articles_bp.route("/", methods=["GET", "POST"])
@is_logged_in
def index():
    return data_article()


# analytic
@analytics_bp.route("/")
@is_logged_in
def index():
    return data_analytic()


@auth_bp.route("/logout")
def logout():
    return auth_logout()

app/controller/auth.py
from flask import flash, redirect, render_template, request, session, url_for
from app.config.utils import mysql, MySQLdb


def auth_index():
    if "logged_in" in session:
        return redirect(url_for("dashboard.index"))
    else:
        return redirect(url_for("auth.index"))


def auth_logout():
    if "id_user" in session:
        cur = mysql.connection.cursor()
        cur.execute(
            "UPDATE tb_user SET login_status = 0 WHERE id_user = %s",
            (session["id_user"],),
        )
        mysql.connection.commit()
        cur.close()

    session.clear()
    flash("Anda telah logout.", "success")
    return redirect(url_for("auth.index"))


def auth_login():
    title = "Login - Online Media Monitoring"
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        ip_address = request.remote_addr

        cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cur.execute(
            "SELECT * FROM tb_user WHERE username=%s AND password=%s",
            (username, password),
        )
        data = cur.fetchone()

        if data:
            if data["login_status"] == 1:
                flash(
                    "Akun sedang digunakan. Tidak dapat login di beberapa perangkat.",
                    "danger",
                )
                return redirect(url_for("auth.index"))

            cur.execute(
                """
                UPDATE tb_user
                SET login_status = 1, ip_address = %s WHERE id_user = %s
            """,
                (ip_address, data["id_user"]),
            )
            mysql.connection.commit()

            session["logged_in"] = True
            session["id_user"] = data["id_user"]
            session["nama"] = data["nama"]
            session["email"] = data["email"]
            session["username"] = data["username"]
            session["role"] = data["role"]
            session["profile"] = data["profile"]
            session["ip_address"] = ip_address

            flash("Login berhasil!", "success")
            return redirect(url_for("dashboard.index"))

        flash("Username atau password salah!", "danger")
    return render_template("auth/index.html", title=title)

app/templates/analytic/analytic.html
{% extends 'main.html' %}
{% block title%} {{ session.role }} - Analytic {%endblock %}
{% block content%}
<div class="row">
    <div class="row mb-6">
        <div class="col-md">
            <div class="card">
                <div class="card-body">
                    <div id="conventionalMediaTrend" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-6">
        <div class="col-md">
            <div class="card">
                <div class="card-body">
                    <div id="groupMediaTrend" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-6">
        <div class="col-md">
            <div class="card">
                <div class="card-body">
                    <div id="overallSentimentPieChart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                </div>
            </div>
        </div>
        <div class="col-md">
            <div class="card">
                <div class="card-body">
                    <div id="sentimentByGroupBasicChart" style="min-width: 310px; height: 400px; margin: 0 auto">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-6">
        <div class="col-md">
            <div class="card">
                <div class="card-body">
                    <div id="conventionalGroupType" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock %}

app/templates/article/article.html
{% extends 'main.html' %}
{% block title%} {{ session.role }} - Article {%endblock %}
{% block content%}
<div class="card">
    <div class="d-flex justify-content-between align-items-center">
        <h5 class="card-header">Data Article {{ daterange }}</h5>

        <div class="d-flex align-items-center">
            <button type="button" class="btn btn-primary me-3">
                <span class="tf-icons bx bx-export bx-22px"></span>
                Ekspor Data
            </button>
        </div>
    </div>
    <div class="card-datatable table-responsive pt-0">
        <table id="myTable" class="datatables-basic table border-top">
            <thead>
                <tr>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>

                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{%endblock %}

app/templates/dashboard/index.html
{% extends 'main.html' %}
{% block title%} {{ session.role }} - Dashboard {%endblock %}
{% block content%}
<div class="row">
    <div class="mb-6 order-0">
        <div class="card">
            <div class="d-flex align-items-start row">
                <div class="card">
                    <div class="card-widget-separator-wrapper">
                        <div class="card-body card-widget-separator">
                            <div class="row gy-4 gy-sm-1">
                                <div class="col-sm-6 col-lg-3">
                                    <div
                                        class="d-flex justify-content-between align-items-center card-widget-1 border-end pb-4 pb-sm-0">
                                        <div>
                                            <h4 class="mb-0" id="article-count"></h4>
                                            <p class="mb-0">Media Online</p>
                                        </div>
                                        <div class="avatar me-sm-6">
                                            <span class="avatar-initial rounded bg-label-secondary text-heading">
                                                <i class="bx bx-news bx-26px"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <hr class="d-none d-sm-block d-lg-none me-6" />
                                </div>
                                <div class="col-sm-6 col-lg-3">
                                    <div
                                        class="d-flex justify-content-between align-items-center card-widget-2 border-end pb-4 pb-sm-0">
                                        <div>
                                            <h4 class="mb-0">0</h4>
                                            <p class="mb-0">Media Cetak</p>
                                        </div>
                                        <div class="avatar me-lg-6">
                                            <span class="avatar-initial rounded bg-label-secondary text-heading">
                                                <i class="bx bx-world bx-26px"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <hr class="d-none d-sm-block d-lg-none" />
                                </div>
                                <div class="col-sm-6 col-lg-3">
                                    <!-- <div
                                        class="d-flex justify-content-between align-items-center border-end pb-4 pb-sm-0 card-widget-3">
                                        <div>
                                            <h4 class="mb-0">0</h4>
                                            <p class="mb-0">Jumlah Engagement</p>
                                        </div>
                                        <div class="avatar me-sm-6">
                                            <span class="avatar-initial rounded bg-label-secondary text-heading">
                                                <i class="bx bx-stats bx-26px"></i>
                                            </span>
                                        </div>
                                    </div> -->
                                </div>
                                <div class="col-sm-6 col-lg-3">
                                    <!-- <div class="d-flex justify-content-between align-items-center">
                                        <div>
                                            <h4 class="mb-0">0</h4>
                                            <p class="mb-0">Jumlah Reach</p>
                                        </div>
                                        <div class="avatar">
                                            <span class="avatar-initial rounded bg-label-secondary text-heading">
                                                <i class="bx bxs-megaphone bx-26px"></i>
                                            </span>
                                        </div>
                                    </div> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="card-body">
                        <h5 class="card-title text-primary mb-3">
                            Welcome ! {{ session.nama }}🎉
                            <!-- Display the global daterange -->
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-6">
        <div class="col-md">
            <div class="card">
                <div class="card-body">
                    <div id="conventionalMediaTrend" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-6">
        <div class="col-md">
            <div class="card">
                <div class="card-body">
                    <div id="overallSentimentPieChart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                </div>
            </div>
        </div>
        <div class="col-md">
            <div class="card">
                <div class="card-body">
                    <div id="sentimentByGroupBasicChart" style="min-width: 310px; height: 400px; margin: 0 auto">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock %}

app/templates/main.html
<!DOCTYPE html>
<html lang="en" class="light-style layout-menu-fixed layout-compact" dir="ltr" data-theme="theme-default">

<head>
  <meta charset="utf-8" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

  <title>{% block title%} {%endblock %}</title>

  <meta name="description" content="" />

  <!-- Favicon -->
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon/favicon.ico') }}" />

  <!-- Style -->
  {% include 'partial/style.html' %}

</head>

<body>

  <!-- SPINNER LOADING -->
  {% include 'partial/spinner.html' %}

  <!-- NOTIFICATIONS LOADING -->
  {% include 'partial/notif.html' %}

  <!-- Layout wrapper -->
  <div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">
      <!-- Menu -->
      {% include 'partial/menu.html' %}
      <!-- / Menu -->

      <!-- Layout container -->
      <div class="layout-page">
        <!-- Navbar -->
        {% include 'partial/navbar.html' %}
        <!-- / Navbar -->

        <!-- Content wrapper -->
        <div class="content-wrapper">
          <!-- Content -->
          <div class="container-xxl flex-grow-1 container-p-y">
            {% block content%} {%endblock %}
          </div>
          <!-- / Content -->

          <!-- Footer -->
          {% include 'partial/footer.html' %}
          <!-- / Footer -->

          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
  </div>
  {% include 'partial/script.html' %}
</body>

</html>

app/templates/partial/footer.html
{% block footer%}
<footer class="content-footer footer bg-footer-theme">
    <div class="container-xxl">
        <div class="footer-container d-flex align-items-center justify-content-between py-4 flex-md-row flex-column">
            <div class="text-body">
                ©
                <script>
                    document.write(new Date().getFullYear());
                </script>
                , made with ❤️ by
                <a href="http://svlad.rf.gd/" target="_blank" class="footer-link">SVLAD</a>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

app/templates/partial/menu.html
{% block menu %}
{% if session.role == 'Administrator' %}
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo d-flex align-items-center">
        <a href="{{ url_for('dashboard.index') }}" class="app-brand-link d-flex align-items-center">
            <span class="app-brand-logo demo">
                <!-- SVG logo content -->
            </span>
            <span class="app-brand-text demo menu-text fw-bold ms-2">sneat</span>
        </a>
        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm d-flex align-items-center justify-content-center"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <!-- Menu List -->
    <ul class="menu-inner py-1">
        <!-- Dashboard Menu -->
        <li class="menu-item {% if request.endpoint == 'dashboard.index' %}active{% endif %}">
            <a href="{{ url_for('dashboard.index') }}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-smile"></i>
                <div class="text-truncate">Dashboards</div>
            </a>
        </li>

        <!-- Group Section -->
        <li class="menu-header small text-uppercase">
            <span class="menu-header-text">Group Section</span>
        </li>
        <li class="menu-item {% if request.endpoint == 'group.index' %}active{% endif %}">
            <a href="{{ url_for('group.index') }}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-filter"></i>
                <div class="text-truncate">Group</div>
            </a>
        </li>

        <!-- User Section -->
        <li class="menu-header small text-uppercase">
            <span class="menu-header-text">User Section</span>
        </li>
        <li
            class="menu-item {% if request.endpoint in ['user.admin', 'user.operator', 'user.viewer'] %}active open{% endif %}">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bx-group"></i>
                <div class="text-truncate">Data User</div>
            </a>
            <ul class="menu-sub">
                <!-- Admin Menu -->
                <li class="menu-item {% if request.endpoint == 'user.admin' %}active{% endif %}">
                    <a href="{{ url_for('user.admin') }}" class="menu-link">
                        <div class="text-truncate">Admin</div>
                    </a>
                </li>
                <!-- Operator Menu -->
                <li class="menu-item {% if request.endpoint == 'user.operator' %}active{% endif %}">
                    <a href="{{ url_for('user.operator') }}" class="menu-link">
                        <div class="text-truncate">Operator</div>
                    </a>
                </li>
                <!-- Viewer Menu -->
                <li class="menu-item {% if request.endpoint == 'user.viewer' %}active{% endif %}">
                    <a href="{{ url_for('user.viewer') }}" class="menu-link">
                        <div class="text-truncate">Viewer</div>
                    </a>
                </li>
            </ul>
        </li>

        <!-- Article Section -->
        <li class="menu-header small text-uppercase">
            <span class="menu-header-text">Article Section</span>
        </li>
        <li class="menu-item {% if request.endpoint == 'article.index' %}active{% endif %}">
            <a href="{{ url_for('article.index') }}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-file"></i>
                <div class="text-truncate">Article</div>
            </a>
        </li>

        <!-- Analytic Section -->
        <li class="menu-header small text-uppercase">
            <span class="menu-header-text">Analytic Section</span>
        </li>
        <li class="menu-item {% if request.endpoint == 'analytic.index' %}active{% endif %}">
            <a href="{{ url_for('analytic.index') }}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-chart"></i>
                <div class="text-truncate">Analytic</div>
            </a>
        </li>
    </ul>
</aside>
{% else %}
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo d-flex align-items-center">
        <a href="{{ url_for('dashboard.index') }}" class="app-brand-link d-flex align-items-center">
            <span class="app-brand-logo demo">
                <!-- SVG logo content -->
            </span>
            <span class="app-brand-text demo menu-text fw-bold ms-2">sneat</span>
        </a>
        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm d-flex align-items-center justify-content-center"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <!-- Menu List -->
    <ul class="menu-inner py-1">
        <!-- Dashboard Menu -->
        <li class="menu-item {% if request.endpoint == 'dashboard.index' %}active{% endif %}">
            <a href="{{ url_for('dashboard.index') }}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-smile"></i>
                <div class="text-truncate">Dashboards</div>
            </a>
        </li>

        <!-- Article Section -->
        <li class="menu-header small text-uppercase">
            <span class="menu-header-text">Article Section</span>
        </li>
        <li class="menu-item {% if request.endpoint == 'article.index' %}active{% endif %}">
            <a href="{{ url_for('article.index') }}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-file"></i>
                <div class="text-truncate">Article</div>
            </a>
        </li>

        <!-- Analytic Section -->
        <li class="menu-header small text-uppercase">
            <span class="menu-header-text">Analytic Section</span>
        </li>
        <li class="menu-item {% if request.endpoint == 'analytic.index' %}active{% endif %}">
            <a href="{{ url_for('analytic.index') }}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-chart"></i>
                <div class="text-truncate">Analytic</div>
            </a>
        </li>
    </ul>
</aside>
{% endif %}
{% endblock %}

app/templates/partial/navbar.html
{% block navbar%}
<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
    id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-4 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-6" href="javascript:void(0)">
            <i class="bx bx-menu bx-md"></i>
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
        <div class="navbar-nav align-items-center">
            <div class="nav-item d-flex align-items-center me-3">
                <select name="group" id="group" multiple multiselect-search="true" multiselect-select-all="true"
                    multiselect-max-items="3" style="min-width: 500px">
                    {% for group in groups %}
                    <option value="{{ group.nama_group }}" selected>
                        {{ group.nama_group }}
                    </option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="navbar-nav align-items-center">
            <div class="nav-item d-flex align-items-center me-3">
                <input class="form-control form-control-solid" name="daterange" placeholder="Pick date rage"
                    id="reportrange" />
            </div>
        </div>
        <ul class="navbar-nav flex-row align-items-center ms-auto">
            <!-- User -->
            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                <a class="nav-link dropdown-toggle hide-arrow p-0" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                        {% if session.profile is none or session.profile == '' %}
                        <img src="{{ url_for('static', filename='profile/user.png') }}" alt
                            class="w-px-40 rounded-circle" />
                        {% else %}
                        <img alt class="w-px-40 rounded-circle"
                            src="{{ url_for('static', filename='profile/' + session.profile) }}" />
                        {% endif %}
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <a class="dropdown-item" href="#">
                            <div class="d-flex">
                                <div class="flex-shrink-0 me-3">
                                    <div class="avatar avatar-online">
                                        {% if session.profile is none or session.profile == '' %}
                                        <img src="{{ url_for('static', filename='profile/user.png') }}" alt
                                            class="w-px-40 rounded-circle" />
                                        {% else %}
                                        <img alt class="w-px-40 rounded-circle"
                                            src="{{ url_for('static', filename='profile/' + session.profile) }}" />
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-0">{{ session.nama }}</h6>
                                    <small class="text-muted">{{ session.role }}</small>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider my-1"></div>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{{ url_for('setting.profile') }}">
                            <i class="bx bx-user bx-md me-3"></i><span>My Profile</span>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider my-1"></div>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                            <i class="bx bx-power-off bx-md me-3"></i><span>Log Out</span>
                        </a>
                    </li>
                </ul>
            </li>
            <!--/ User -->
        </ul>
    </div>
</nav>
{% endblock %}

app/templates/partial/notif.html
{% block notif%}

{% with messages = get_flashed_messages(with_categories=true) %} {% if messages %}
{% for category, message in messages %}
<div class="alert alert-dismissible alert-{{ category }}" data-notify-position="bottom-right" style="
            display: inline-block;
            margin: 0px auto;
            position: fixed;
            transition: 0.5s ease-in-out;
            z-index: 1031;
            bottom: 20px;
            right: 20px;
        ">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <span data-notify="message"> {{ message }} </span>
</div>
<script>
    setTimeout(function () {
        document.querySelector(".alert").style.display = "none";
    }, 5000);
</script>
{% endfor %} {% endif %} {% endwith %}

{% endblock %}

app/templates/partial/spinner.html
{% block spinner%}
<!-- Tambahkan spinner -->
<div id="loading-spinner1" class="loading-overlay" style="display: none;">
    <div class="spinner-box">
        <div class="blue-orbit leo"></div>
        <div class="green-orbit leo"></div>
        <div class="red-orbit leo"></div>
        <div class="white-orbit w1 leo"></div>
        <div class="white-orbit w2 leo"></div>
        <div class="white-orbit w3 leo"></div>
    </div>
</div>

<div id="loading-spinner" class="loading-overlay">
    <div class="spinner-box">
        <div class="blue-orbit leo"></div>
        <div class="green-orbit leo"></div>
        <div class="red-orbit leo"></div>
        <div class="white-orbit w1 leo"></div>
        <div class="white-orbit w2 leo"></div>
        <div class="white-orbit w3 leo"></div>
    </div>
</div>

<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {
        // Ambil elemen spinner dan konten utama
        const loadingSpinner = document.getElementById("loading-spinner");
        const mainContent = document.getElementById("layout-wrapper");

        // Sembunyikan spinner dan tampilkan konten utama
        setTimeout(() => {
            loadingSpinner.style.display = "none";
            mainContent.style.display = "block";
        }, 1000); // Waktu delay untuk loading (1 detik, bisa disesuaikan)
    });
</script>
{% endblock %}

app/templates/partial/style.html
{% block style%}
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
    href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
    rel="stylesheet" />
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/fonts/boxicons.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/css/core.css') }}"
    class="template-customizer-core-css" />
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/css/theme-default.css') }}"
    class="template-customizer-theme-css" />
<link rel="stylesheet" href="{{ url_for('static', filename='css/demo.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/libs/perfect-scrollbar/perfect-scrollbar.css') }}" />
<script src="{{ url_for('static', filename='vendor/js/helpers.js') }}"></script>
<script src="{{ url_for('static', filename='js/config.js') }}"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.min.css" />

{% endblock %}